# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaled_betaPDF <- function(y, low, high, shape1, shape2) {
    .Call('_OPER782_scaled_betaPDF', PACKAGE = 'OPER782', y, low, high, shape1, shape2)
}

rcpp_hello_world <- function() {
    .Call('_OPER782_rcpp_hello_world', PACKAGE = 'OPER782')
}

